id: I3F770F6C
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:13:26.651527
last_modified: 2023-02-08 15:13:26.651634
source_metadata:
  title: Mañjuśrīvikrīḍitasūtra
  language: zh
bases:
  7DB7:
    base_file: 7DB7.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
